version: "3.3"
services:
  challenge:
    container_name: "blockchain_rolls-royce"
    image: chainflag/eth-challenge-base:0.9.3
    ports:
      - "20003:20000"
    env_file:
      - ../.env
    volumes:
      - ./contracts:/home/ctf/contracts
      - ./challenge.yml:/home/ctf/challenge.yml
    networks:
      - network_fibo

networks:
  network_fibo:
    name: network_fibo_default
    external: true
